apiVersion: s3.onyxia.sh.onyxia.sh/v1alpha1
kind: Path
metadata:
  labels:
    app.kubernetes.io/name: path
    app.kubernetes.io/instance: path-sample
    app.kubernetes.io/part-of: s3-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: s3-operator
  name: path-sample
spec:
  # TODO(user): Add fields here
